FROM python:3.8

RUN apt-get update


RUN mkdir fastapi_service
ADD /fastapi_service/ml_bot.py fastapi_service/ml_bot.py
ADD /fastapi_service/predictor.py fastapi_service/predictor.py
ADD /fastapi_service/transaction.py fastapi_service/transaction.py
ADD /fastapi_service/metrics_utils.py fastapi_service/metrics_utils.py

RUN mkdir /anomaly
RUN mkdir /anomaly/data_preprocessing
ADD /anomaly/data_preprocessing/. /anomaly/data_preprocessing/.
ADD /anomaly/models_pkl /anomaly/models_pkl
ADD /anomaly/models.py /anomaly/models.py


ADD /requirements.txt /requirements.txt


RUN pip install --upgrade pip
RUN pip install --upgrade setuptools
RUN pip install -r requirements.txt
ENV PYTHONPATH "${PYTHONPATH}:."
CMD ["python3", "fastapi_service/ml_bot.py"]
